services:
  - type: web
    name: for-you
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: Sathee.Singh
      - key: ADMIN_PASSWORD
        value: Loveusubham
      - key: REQUIRE_LOGIN
        value: "true"

